-- =============================================================================
-- Módulos: cart + order (pedidos, pagos, preparación, devoluciones, historial)
-- =============================================================================

create table public.cart (
  id uuid primary key default gen_random_uuid(),
  email text,
  customer_id uuid references public.customer (id) on delete set null,
  region_id uuid references public.region (id) on delete set null,
  sales_channel_id uuid references public.sales_channel (id) on delete set null,
  currency_code text not null references public.currency (code),
  shipping_address jsonb,
  billing_address jsonb,
  metadata jsonb not null default '{}',
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger cart_updated_at before update on public.cart for each row execute function internal.set_updated_at();

create table public.cart_line_item (
  id uuid primary key default gen_random_uuid(),
  cart_id uuid not null references public.cart (id) on delete cascade,
  variant_id uuid references public.product_variant (id) on delete set null,
  product_id uuid references public.product (id) on delete set null,
  quantity int not null check (quantity > 0),
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create table public.cart_shipping_method (
  id uuid primary key default gen_random_uuid(),
  cart_id uuid not null references public.cart (id) on delete cascade,
  shipping_option_id uuid references public.shipping_option (id) on delete set null,
  data jsonb not null default '{}'
);

create table public.cart_promotion (
  cart_id uuid not null references public.cart (id) on delete cascade,
  promotion_id uuid not null references public.promotion (id) on delete cascade,
  primary key (cart_id, promotion_id)
);

create type public.order_status as enum ('pending', 'completed', 'canceled', 'archived', 'requires_action');
create type public.payment_status as enum ('not_paid', 'awaiting', 'authorized', 'partially_captured', 'captured', 'partially_refunded', 'refunded', 'canceled');
create type public.fulfillment_status as enum ('not_fulfilled', 'partially_fulfilled', 'fulfilled', 'shipped', 'delivered', 'canceled');

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  display_id bigint generated by default as identity (start with 1001) unique,
  status public.order_status not null default 'pending',
  payment_status public.payment_status not null default 'not_paid',
  fulfillment_status public.fulfillment_status not null default 'not_fulfilled',
  customer_id uuid references public.customer (id) on delete set null,
  email text not null,
  phone text,
  region_id uuid references public.region (id) on delete set null,
  sales_channel_id uuid references public.sales_channel (id) on delete set null,
  currency_code text not null references public.currency (code),
  shipping_address jsonb,
  billing_address jsonb,
  -- Totales guardados al crear el pedido (instantánea contable).
  subtotal numeric(12, 2) not null default 0,
  discount_total numeric(12, 2) not null default 0,
  shipping_total numeric(12, 2) not null default 0,
  tax_total numeric(12, 2) not null default 0,       -- IGV incluido en el total
  total numeric(12, 2) not null default 0,
  paid_total numeric(12, 2) not null default 0,
  refunded_total numeric(12, 2) not null default 0,
  item_count int not null default 0,
  note text,                     -- nota del cliente
  tags text[] not null default '{}',
  source text not null default 'web',                -- web | admin | whatsapp | pos
  cart_id uuid references public.cart (id) on delete set null,
  canceled_at timestamptz,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index orders_created_idx on public.orders (created_at desc);
create index orders_customer_idx on public.orders (customer_id);
create trigger orders_updated_at before update on public.orders for each row execute function internal.set_updated_at();

create table public.order_line_item (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  variant_id uuid references public.product_variant (id) on delete set null,
  product_id uuid references public.product (id) on delete set null,
  title text not null,
  subtitle text,                 -- título de la variante
  sku text,
  thumbnail text,
  quantity int not null check (quantity > 0),
  unit_price numeric(12, 2) not null,
  compare_at_unit_price numeric(12, 2),
  subtotal numeric(12, 2) generated always as (quantity * unit_price) stored,
  discount_total numeric(12, 2) not null default 0,
  fulfilled_quantity int not null default 0,
  returned_quantity int not null default 0,
  requires_shipping boolean not null default true,
  metadata jsonb not null default '{}',   -- { gift_wrap: true, message: "…" }
  created_at timestamptz not null default now()
);
create index order_line_item_order_idx on public.order_line_item (order_id);

alter table public.reservation_item
  add constraint reservation_item_line_item_fk foreign key (line_item_id) references public.order_line_item (id) on delete cascade;

create table public.order_shipping_method (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  shipping_option_id uuid references public.shipping_option (id) on delete set null,
  name text not null,
  amount numeric(12, 2) not null default 0,
  is_pickup boolean not null default false,
  stock_location_id uuid references public.stock_location (id) on delete set null,
  data jsonb not null default '{}'
);

create type public.transaction_kind as enum ('authorization', 'capture', 'refund', 'void');
create type public.transaction_status as enum ('pending', 'success', 'failure');

create table public.order_transaction (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  kind public.transaction_kind not null,
  status public.transaction_status not null default 'success',
  provider text not null,          -- card | yape | plin | transfer | cash
  amount numeric(12, 2) not null,
  currency_code text not null references public.currency (code),
  reference text,
  note text,
  created_by uuid,
  created_at timestamptz not null default now()
);
create index order_transaction_order_idx on public.order_transaction (order_id);

create table public.order_promotion (
  order_id uuid not null references public.orders (id) on delete cascade,
  promotion_id uuid references public.promotion (id) on delete set null,
  code text not null,
  amount numeric(12, 2) not null default 0,
  primary key (order_id, code)
);

create table public.fulfillment (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  location_id uuid references public.stock_location (id) on delete set null,
  provider text not null default 'manual',
  tracking_company text,
  tracking_number text,
  tracking_url text,
  packed_at timestamptz,
  shipped_at timestamptz,
  delivered_at timestamptz,
  canceled_at timestamptz,
  created_by uuid,
  created_at timestamptz not null default now()
);
create index fulfillment_order_idx on public.fulfillment (order_id);

create table public.fulfillment_item (
  id uuid primary key default gen_random_uuid(),
  fulfillment_id uuid not null references public.fulfillment (id) on delete cascade,
  line_item_id uuid not null references public.order_line_item (id) on delete cascade,
  quantity int not null check (quantity > 0)
);

create type public.return_status as enum ('requested', 'received', 'canceled');

create table public.order_return (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  status public.return_status not null default 'requested',
  reason text,
  refund_amount numeric(12, 2) not null default 0,
  location_id uuid references public.stock_location (id) on delete set null,
  received_at timestamptz,
  created_by uuid,
  created_at timestamptz not null default now()
);

create table public.return_item (
  id uuid primary key default gen_random_uuid(),
  return_id uuid not null references public.order_return (id) on delete cascade,
  line_item_id uuid not null references public.order_line_item (id) on delete cascade,
  quantity int not null check (quantity > 0),
  reason text
);

-- Línea de tiempo del pedido (eventos del sistema + comentarios del equipo).
create table public.order_event (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  type text not null,              -- placed | paid | fulfilled | shipped | delivered | canceled | refunded | note | edited
  message text not null,
  data jsonb not null default '{}',
  actor_id uuid,
  created_at timestamptz not null default now()
);
create index order_event_order_idx on public.order_event (order_id, created_at desc);
