-- =============================================================================
-- Libro de reclamaciones virtual (Código de Protección y Defensa del Consumidor, Ley 29571,
-- y su reglamento, D.S. 011-2011-PCM)
--   complaint                -> hojas de reclamación con correlativo LR-AAAA-000001
--   store_submit_complaint   -> la tienda registra una hoja (anon o con sesión)
--   admin_answer_complaint   -> el panel registra la respuesta al consumidor
-- =============================================================================

create type public.complaint_kind as enum ('reclamo', 'queja');
create type public.complaint_status as enum ('pendiente', 'en_proceso', 'respondido');

create table public.complaint (
  id uuid primary key default gen_random_uuid(),
  number bigint generated by default as identity (start with 1) unique,
  code text not null unique,                       -- LR-2026-000001
  -- 1. Consumidor reclamante
  first_name text not null,
  last_name text not null,
  document_type text not null check (document_type in ('DNI', 'CE', 'Pasaporte', 'RUC')),
  document_number text not null,
  email text not null,
  phone text not null,
  address text not null,
  department text,
  province text,
  district text,
  is_minor boolean not null default false,
  guardian_name text,                              -- padre, madre o apoderado si es menor de edad
  -- 2. Bien contratado
  item_type text not null check (item_type in ('producto', 'servicio')),
  item_description text not null,
  amount numeric(12, 2),
  order_reference text,
  -- 3. Detalle
  kind public.complaint_kind not null,
  detail text not null,
  request text not null,                           -- pedido del consumidor
  -- 4. Respuesta del proveedor
  status public.complaint_status not null default 'pendiente',
  response text,
  responded_at timestamptz,
  customer_id uuid references public.customer (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint complaint_guardian check (not is_minor or guardian_name is not null)
);
create index complaint_created_idx on public.complaint (created_at desc);
create index complaint_status_idx on public.complaint (status);
create trigger complaint_updated_at before update on public.complaint for each row execute function internal.set_updated_at();

-- Solo los administradores leen y editan. La tienda escribe mediante store_submit_complaint.
alter table public.complaint enable row level security;
create policy admin_all on public.complaint for all to authenticated using (internal.is_admin()) with check (internal.is_admin());

-- Registra una hoja de reclamación y devuelve su código correlativo.
--   p = { first_name, last_name, document_type, document_number, email, phone, address,
--         department?, province?, district?, is_minor?, guardian_name?,
--         item_type, item_description, amount?, order_reference?, kind, detail, request }
create or replace function public.store_submit_complaint(p jsonb) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_row public.complaint;
  v_number bigint;
  v_field text;
begin
  foreach v_field in array array['first_name', 'last_name', 'document_type', 'document_number', 'email', 'phone', 'address',
                                 'item_type', 'item_description', 'kind', 'detail', 'request'] loop
    if nullif(trim(p->>v_field), '') is null then
      raise exception 'Falta completar: %', v_field using errcode = '22023';
    end if;
  end loop;
  if length(p->>'detail') > 5000 or length(p->>'request') > 5000 then
    raise exception 'El detalle y el pedido deben tener como máximo 5000 caracteres' using errcode = '22023';
  end if;
  if coalesce((p->>'is_minor')::boolean, false) and nullif(trim(p->>'guardian_name'), '') is null then
    raise exception 'Si eres menor de edad, indica el nombre de tu padre, madre o apoderado' using errcode = '22023';
  end if;

  v_number := nextval(pg_get_serial_sequence('public.complaint', 'number'));
  insert into public.complaint (
    number, code, first_name, last_name, document_type, document_number, email, phone, address,
    department, province, district, is_minor, guardian_name,
    item_type, item_description, amount, order_reference, kind, detail, request, customer_id
  ) values (
    v_number,
    'LR-' || to_char(now() at time zone 'America/Lima', 'YYYY') || '-' || lpad(v_number::text, 6, '0'),
    trim(p->>'first_name'), trim(p->>'last_name'), p->>'document_type', trim(p->>'document_number'),
    lower(trim(p->>'email')), trim(p->>'phone'), trim(p->>'address'),
    nullif(trim(p->>'department'), ''), nullif(trim(p->>'province'), ''), nullif(trim(p->>'district'), ''),
    coalesce((p->>'is_minor')::boolean, false), nullif(trim(p->>'guardian_name'), ''),
    p->>'item_type', trim(p->>'item_description'), nullif(p->>'amount', '')::numeric, nullif(trim(p->>'order_reference'), ''),
    (p->>'kind')::public.complaint_kind, trim(p->>'detail'), trim(p->>'request'),
    (select id from public.customer where auth_user_id = auth.uid() and auth.uid() is not null)
  ) returning * into v_row;

  return jsonb_build_object('id', v_row.id, 'code', v_row.code, 'created_at', v_row.created_at);
end $$;

-- Registra (o corrige) la respuesta del proveedor a una hoja.
create or replace function public.admin_answer_complaint(p_id uuid, p_response text) returns public.complaint
language plpgsql security definer set search_path = public as $$
declare v_row public.complaint;
begin
  perform internal.assert_admin();
  if nullif(trim(p_response), '') is null then raise exception 'Escribe la respuesta' using errcode = '22023'; end if;
  update public.complaint
     set response = trim(p_response), status = 'respondido', responded_at = coalesce(responded_at, now())
   where id = p_id
  returning * into v_row;
  if v_row.id is null then raise exception 'Reclamo no encontrado' using errcode = 'P0002'; end if;
  return v_row;
end $$;

revoke all on function public.store_submit_complaint(jsonb) from public;
revoke all on function public.admin_answer_complaint(uuid, text) from public;
grant execute on function public.store_submit_complaint(jsonb) to anon, authenticated;
grant execute on function public.admin_answer_complaint(uuid, text) to authenticated;
